#naver.url.search.local=https://openapi.naver.com/v1/search/local.json
#naver.url.search.image=https://openapi.naver.com/v1/search/image.json

naver.client.secret=${X_NAVER_CLIENT_SECRET}
spring.datasource.url=jdbc:mysql://localhost:3306/api?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.thymeleaf.cache=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
